// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAohAA2_c8JrgDkTu3OpFTHfV-2VMStAVg',
    appId: '1:790974634846:web:bdca400c2e08898e598dcf',
    messagingSenderId: '790974634846',
    projectId: 'medical-motor-automobile',
    authDomain: 'medical-motor-automobile.firebaseapp.com',
    storageBucket: 'medical-motor-automobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtXhrrvTBHVV0QDpjKj-dTuvAhFQXWGI',
    appId: '1:790974634846:android:cb0e8cfd53ca5c32598dcf',
    messagingSenderId: '790974634846',
    projectId: 'medical-motor-automobile',
    storageBucket: 'medical-motor-automobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP49e8UL1Fz4ftnM9a4tIpSbdlWarg8Vc',
    appId: '1:790974634846:ios:8a9ce1a527757bf1598dcf',
    messagingSenderId: '790974634846',
    projectId: 'medical-motor-automobile',
    storageBucket: 'medical-motor-automobile.firebasestorage.app',
    iosBundleId: 'com.example.voitureAutonome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP49e8UL1Fz4ftnM9a4tIpSbdlWarg8Vc',
    appId: '1:790974634846:ios:8a9ce1a527757bf1598dcf',
    messagingSenderId: '790974634846',
    projectId: 'medical-motor-automobile',
    storageBucket: 'medical-motor-automobile.firebasestorage.app',
    iosBundleId: 'com.example.voitureAutonome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAohAA2_c8JrgDkTu3OpFTHfV-2VMStAVg',
    appId: '1:790974634846:web:ee13b06acd54c2fc598dcf',
    messagingSenderId: '790974634846',
    projectId: 'medical-motor-automobile',
    authDomain: 'medical-motor-automobile.firebaseapp.com',
    storageBucket: 'medical-motor-automobile.firebasestorage.app',
  );
}
